#!/bin/ksh
pd=`/bin/pwd`
export DESTDIR=$pd/dest
export RELEASEDIR=$pd/rel

log=$pd/snap.log
if [ -f $log ]
then

	i=0
while [	 -f $log.$i ]
	do
		let i=i+1
	done
	log=$log.$i
fi
sh -c "(echo \$\$ > ${log}.lock ; make && make release; rm ${log}.lock) > $log 2>&1 &"
sleep 10
while [ -f ${log}.lock ]
do
	tail -2 $log
	sleep 120
done
