
LIBS	=  -L${PREFIX}/lib -lXext -lX11 -lXmu -lm

CC	= gcc
CCC	= gcc
CFLAGS	= -O2 -I${PREFIX}/include
OBJECTS	= Border.o Buttons.o Client.o Events.o Main.o Manager.o Rotated.o

.c.o:
	$(CC) -c $(CFLAGS) $<

.C.o:
	$(CCC) -c $(CFLAGS) $<

wm2:	$(OBJECTS)
	mv -f wm2 wm2.old > /dev/null 2>&1 || true
	$(CCC) -o wm2 $(OBJECTS) $(LIBS)

install:
	${BSD_INSTALL_PROGRAM} wm2 ${PREFIX}/bin

depend:
	makedepend -- $(CFLAGS) -- *.C

clean:
	rm -f *.o core

distclean: clean
	rm -f wm2 wm2.old *~

