#!/bin/csh -f

set arch=`machine`
set listsdir=`pwd`/lists

set TMPFILE=/tmp/_LIST.$$

set lists=(xbase xserv)
# SPECIAL: man misc
# EXTRA SPECIAL (not done here): secr

foreach setname ($lists)
	cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} >>! $TMPFILE
end

if ( "$arch" == "i386" ) then
    set setname=xlink
    cat $listsdir/$setname/mi $listsdir/$setname/md.${arch} >>! $TMPFILE
endif

sort $TMPFILE
/bin/rm $TMPFILE
